//using Doggie.Context;
//using Doggie.Modelsss.BaseMode;
//using IronBarCode;
//using Microsoft.AspNetCore.Mvc;
//using Microsoft.AspNetCore.Razor.Language.CodeGeneration;
//using QRCoder;
//using System.Drawing;
//using System.IO;
//namespace Doggie.Controllers
//{
//	public class QrkodController : Controller
//	{

//        private readonly IWebHostEnvironment _environment;
//        private readonly DoggieFriend _context;
//        public QrkodController(IWebHostEnvironment environment, DoggieFriend context)
//        {
//            _environment = environment;
//            _context = context;     
//        }
//        [HttpGet]
//        public IActionResult CreateQRCode()
//        {
//            return View();
//        }
//        [HttpPost]
//        public IActionResult CreateQRCode(QrCodeModel generateQRCode)
//        {

//            // Creating QR Code
//            GeneratedBarcode barcode = QRCodeWriter.CreateQrCode(generateQRCode.QRCodeText);
//            string path = Path.Combine(_environment.WebRootPath, "GeneratedQRCodee");
//            if (!Directory.Exists(path))
//            {
//                Directory.CreateDirectory(path);
//            }
//            string filePath = Path.Combine(_environment.WebRootPath, "GeneratedQRCodee/qrcode.png");
//            barcode.SaveAsPng(filePath);
//            string fileName = Path.GetFileName(filePath); // qr code file
//            string imageUrl = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}" + "/GeneratedQRCodee/" + fileName;
//            ViewBag.QrCodeUri = imageUrl;

//            barcode.AddAnnotationTextAboveBarcode("QR Code Generated by Iron PDF");
//            barcode.AddBarcodeValueTextBelowBarcode();
//            barcode.ChangeBackgroundColor(Color.White);
//            barcode.ChangeBarCodeColor(Color.MediumVioletRed);




//            return View();
//        }

//        public IActionResult BuyTicket(string id)
//        {

//            foreach (var item in _context.Users)
//            {
//                if (item.Id==id && item.IsUsed==false)
//                {
//                    item.IsUsed = true;
//                    _context.SaveChanges();
//                    return Ok();
                 



//                }
//                if (item.Id == id && item.IsUsed == true)
//                {

//                    return NotFound();




//                }
              


//            }

         


//            return BadRequest();
//        }
//        [HttpGet]
//        public IActionResult Login()
//        {
//            return View();
//        }
//        [HttpPost]
//        public IActionResult Login(string username)
//        {

//            foreach (var item in _context.Users.ToList())
//            {
//                if (item.UserName == username)
//                {
//                    return RedirectToAction("Buyticket", "QrKod", new { id = item.Id });
//                }
//            }


//            return View();
//        }









//    }

//}
